function placeTimePointsOnTraj(yesMean, noMean, omMean, mvStartInd, toneTime, afterToneInd)


if ~isempty(mvStartInd)
    plot3(yesMean(1,mvStartInd), yesMean(2,mvStartInd), yesMean(3,mvStartInd),'ks','MarkerFaceColor','k','MarkerSize',8,...
        'MarkerEdgeColor','k')
end
if ~isempty(toneTime)
    plot3(yesMean(1,toneTime), yesMean(2,toneTime),yesMean(3,toneTime),'ko','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k')
end

if ~isempty(afterToneInd)
    plot3(yesMean(1,afterToneInd), yesMean(2,afterToneInd),yesMean(3,afterToneInd),'k^','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k')
end

if ~isempty(mvStartInd)
    plot3(yesMean(1,mvStartInd), yesMean(2,mvStartInd), yesMean(3,mvStartInd),'ks','MarkerFaceColor','k','MarkerSize',8,...
        'MarkerEdgeColor','k')
end
if ~isempty(toneTime)
    plot3(yesMean(1,toneTime), yesMean(2,toneTime),yesMean(3,toneTime),'ko','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k')
end
if ~isempty(afterToneInd)
    plot3(yesMean(1,afterToneInd), yesMean(2,afterToneInd),yesMean(3,afterToneInd),'k^','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k')
end
if ~isempty(mvStartInd)
    plot3(noMean(1,mvStartInd), noMean(2,mvStartInd),noMean(3,mvStartInd),'ks','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k');
    if ~isempty(omMean) && all(~isnan(omMean(:)))
        plot3(omMean(1,mvStartInd), omMean(2,mvStartInd),omMean(3,mvStartInd),'ks','MarkerSize',8,...
            'MarkerEdgeColor','k',...
            'MarkerFaceColor','k');
    end
end
if ~isempty(toneTime)
    plot3(yesMean(1,toneTime), yesMean(2,toneTime),yesMean(3,toneTime),'ko','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k')
    
    plot3(noMean(1,toneTime), noMean(2,toneTime), noMean(3,toneTime),'ko','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k');
    plot3(noMean(1,afterToneInd), noMean(2,afterToneInd), noMean(3,afterToneInd),'k^','MarkerSize',8,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','k');
    if ~isempty(omMean)  && all(~isnan(omMean(:)))
        plot3(omMean(1,toneTime), omMean(2,toneTime), omMean(3,toneTime),'ko','MarkerSize',8,...
            'MarkerEdgeColor','k',...
            'MarkerFaceColor','k');
        plot3(omMean(1,afterToneInd), omMean(2,afterToneInd), omMean(3,afterToneInd),'k^','MarkerSize',8,...
            'MarkerEdgeColor','k',...
            'MarkerFaceColor','k');
    end
end